# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd069eddde96ce6e67fb1aa40eb09d067d2aa787226aafdb0e040532852f1e876aad3ca33c568c10b48ef1e53320487fe1082c3c1474925d2614ade5b5178107

test:
  secret_key_base: d5749cfe1ef7572a9c60248696bc0dae7d9e5935f04cda2ed74e16ee84a6867a27353d162e72b7d347fb0184b6258323f5783db861f79b75695bf65b7704687a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
